import { z } from 'zod';
import {
  KAI_TOOL_PREFIX,
  cardSchemaNames,
  cardSchemas,
  cardTools,
  isCardSchemaName,
  toolNameForCardType,
} from '@kitn.ai/ui/schemas';
import type { CardSchemaName, ToolProvider } from '@kitn.ai/ui/schemas';
import type { Tool } from './types';
import { cardHostTags, cardTagForType, cardTypeForTag, getElement, listElements } from '../manifest';

/**
 * component_reference — look up AI/UI (kai-*) web components, their props,
 * events, attributes, and CSS custom properties from the live Custom Elements
 * Manifest (dist/custom-elements.json).
 *
 * Backed by manifest.ts which resolves the CEM in both the bundled bin
 * (dist/mcp.es.js sibling) and the Vitest source context (walks up to find
 * dist/custom-elements.json in the repo root).
 *
 * For a card-backed element it also serves the card's JSON Schema and a tool
 * definition GENERATED by `cardTools()`. See `renderCardContract` for why not one
 * byte of that is written here as a literal.
 */

/** Types that warrant the JS-property contract note. */
const JS_ONLY_TYPE_PATTERNS = /\[\]|\{|Record</;

function isJsOnlyType(typeText: string | undefined): boolean {
  return typeText ? JS_ONLY_TYPE_PATTERNS.test(typeText) : false;
}

// ─────────────────────────────────────────────────────────────────────────────
// The card contract
// ─────────────────────────────────────────────────────────────────────────────

const PROVIDERS = ['openai', 'anthropic', 'jsonschema'] as const;

/**
 * What a caller gets when they do not name a provider.
 *
 * NOT a coin-flip between the two wire formats, and deliberately not "serve all
 * three". The three envelopes are not interchangeable in a way a reader can patch
 * up: OpenAI nests the schema at `function.parameters`, Anthropic puts it flat at
 * `input_schema`. Handing over one of those unasked means a harness on the other
 * provider pastes it in and gets a 400 it will blame on the kit.
 *
 * `jsonschema` is the only one of the three that is not a wire envelope at all —
 * `{ name, description, schema }` cannot be mistaken for either provider's shape, so
 * a caller who reads it as one is corrected by the field names before they ship it.
 * It is also directly usable, not a booby prize: `tool({ inputSchema: jsonSchema(
 * def.schema) })` is exactly what the Vercel AI SDK wants, and of the nine
 * integrations this MCP scaffolds, exactly one (openrouter) posts a raw OpenAI-wire
 * tools array; the rest go through an SDK or an agent framework that takes the bare
 * schema.
 *
 * Serving all three was the other candidate and it loses on cost for no gain in
 * safety: measured on this tree, one card's pretty-printed definition runs
 * 1.7-5.3 KB, so three of them plus the schema turns a single `kai-artifact` lookup
 * into roughly 20 KB of context. The response names all three modes and the exact
 * call that produces each, so a caller who does know their provider is one re-ask
 * away and still never invents an envelope.
 */
const DEFAULT_PROVIDER: ToolProvider = 'jsonschema';

function isProvider(value: string): value is ToolProvider {
  return (PROVIDERS as readonly string[]).includes(value);
}

/** Stable fence info strings, so a reader (and reference.test.ts) can lift the blocks back out exactly. */
const TOOL_FENCE = 'kai-tool-definition';
const SCHEMA_FENCE = 'kai-card-schema';

function fence(info: string, value: unknown): string[] {
  return ['```json ' + info, JSON.stringify(value, null, 2), '```'];
}

/**
 * Render a card type as it would be written in JS source.
 *
 * The seven built-ins are all bare identifiers, but a card type is whatever string a
 * developer put in `CardEnvelope.type` — `pricing-table` is legal and reaches this
 * code the day an eighth built-in is hyphenated. Emitting `{ pricing-table: … }` as a
 * copy-paste sample would be a syntax error, so the quoting is decided, not assumed.
 */
const BARE_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function asKey(cardType: string): string {
  return BARE_IDENTIFIER.test(cardType) ? cardType : JSON.stringify(cardType);
}

function asMember(cardType: string): string {
  return BARE_IDENTIFIER.test(cardType) ? `.${cardType}` : `[${JSON.stringify(cardType)}]`;
}

/**
 * The loop, in the four facts a harness cannot infer from a prop table.
 *
 * Shared by the card-backed and the card-host sections because they are the same
 * contract seen from the two ends, and a second copy would be the drift this whole
 * task exists to remove, one level up from the tool definition.
 *
 * `example` is the card the caller actually asked about, so the illustration is about
 * their card rather than a fixed one they then have to translate.
 */
function loopWiring(example: string): string[] {
  return [
    '',
    '#### Wiring the loop',
    `- **Tool names are \`${KAI_TOOL_PREFIX}<card type>\`.** \`${toolNameForCardType(example)}\` produces \`{ type: "${example}" }\`. ` +
      'Use `isCardTool(name)` to split card calls from your own tools; never match the prefix by hand.',
    '- **`tool_call_id` becomes `CardEnvelope.id`, unchanged.** That is what makes a revision UPSERT: ' +
      'a model that re-sends the same tool call id replaces the card in place instead of rendering a second copy of it. ' +
      'Generating your own id breaks that silently.',
    '- **`cardFromToolCall(name, input, { id: call.id })`** turns the call into a renderable envelope, ' +
      'or returns `null` when it is one of your own tools so the loop falls through to it. It never throws.',
    '- **Everything above is one import:** `import { cardTools, cardFromToolCall, isCardTool } from \'@kitn.ai/ui/schemas\'`. ' +
      `The raw documents also ship as JSON (\`@kitn.ai/ui/schemas/${example}.schema.json\`) for a Python or Go backend.`,
  ];
}

/** The card-backed section: schema + a GENERATED tool definition. */
function renderCardContract(tag: string, cardType: CardSchemaName, provider: ToolProvider): string[] {
  const schema = cardSchemas[cardType];

  // GENERATED, NEVER RESTATED.
  //
  // This calls the same `cardTools` a consumer's route calls, on the same schema, so
  // the definition served here cannot diverge from the one they ship — not when a
  // schema gains a field, not when the projection changes what it strips. A literal
  // typed into this file would read identically today and rot on the first schema
  // change, which is exactly the hand-copy drift this tool exists to remove.
  // reference.test.ts asserts byte-equality against BOTH `cardTools({ [type]: schema },
  // …)` and the matching entry of the whole-registry `cardTools({ provider })`, so a
  // hand-edit here fails a test rather than shipping.
  const [def] = cardTools({ [cardType]: schema }, { provider });

  const lines: string[] = [
    '',
    '### Card contract',
    `\`<${tag}>\` renders \`CardEnvelope.type: "${cardType}"\`. A model does not emit an envelope; ` +
      `it calls the tool \`${toolNameForCardType(cardType)}\`, and the kit turns that call back into one.`,
  ];

  lines.push(
    '',
    `#### Tool definition — provider \`${provider}\``,
    `Generated by \`cardTools({ ${asKey(cardType)}: cardSchemas${asMember(cardType)} }, { provider: '${provider}' })\`. ` +
      'Copy it; do not retype it, and do not hand-maintain a second copy — regenerate instead.',
    `Ask again with \`provider\` set to \`openai\`, \`anthropic\` or \`jsonschema\` for the other envelopes. ` +
      'They are NOT interchangeable: OpenAI nests the schema at `function.parameters`, Anthropic puts it flat at `input_schema`.',
    ...fence(TOOL_FENCE, def),
  );

  lines.push(
    '',
    '#### Card data JSON Schema',
    `\`import { cardSchemas } from '@kitn.ai/ui/schemas'\` → \`cardSchemas${asMember(cardType)}\`. ` +
      `Raw document: \`@kitn.ai/ui/schemas/${cardType}.schema.json\`.`,
    'This is the authored contract, and it is what `registry.validate()` checks arriving data against. ' +
      'The tool definition above carries the same document with `$schema`, `$id` and `x-kai-*` stripped — ' +
      'that projection is `cardTools`\' job, so do not put a raw schema on the wire yourself.',
    ...fence(SCHEMA_FENCE, schema),
  );

  lines.push(...loopWiring(cardType));
  return lines;
}

/** The card-host section: no schema of its own, but this is where the props live. */
function renderCardHost(tag: string): string[] {
  const rows = cardSchemaNames.map((type) => {
    const cardTag = cardTagForType(type);
    return `- \`${type}\` → \`<${cardTag ?? '(no element)'}>\`, tool \`${toolNameForCardType(type)}\``;
  });

  return [
    '',
    '### Card contract',
    `\`<${tag}>\` renders generative-UI cards inside the thread. It is a HOST: it draws whatever ` +
      'envelopes arrive, and carries the two props that say what a card may be.',
    '',
    '- **`cardTypes`** — `Record<envelope type, custom element tag>`. What DRAWS a card. ' +
      `Merged over the built-ins, so your entry overrides ours and the other ${cardSchemaNames.length - 1} still render.`,
    '- **`cardSchemas`** — `Record<envelope type, JSON Schema>`. What a VALID card looks like. ' +
      `This is the prop that carries YOUR OWN card schemas into the browser validator; the ${cardSchemaNames.length} built-ins are already known. ` +
      'Both are objects, so both are JS properties (`el.cardSchemas = …`), never HTML attributes.',
    '',
    'Write both once with `createCardRegistry({ use, custom })` from `@kitn.ai/ui/schemas` and thread it to both ends: ' +
      '`el.cardTypes = cards.tags` / `el.cardSchemas = cards.validationSchemas` on the client, `cardTools(cards, { provider })` on the route.',
    '',
    'Built-in card types (ask `component_reference` for one of these tags to get its schema and tool definition):',
    ...rows,
    ...loopWiring(cardSchemaNames[0]),
  ];
}

function formatReference(tag: string, provider: ToolProvider): string {
  const el = getElement(tag);

  if (!el) {
    const all = listElements();
    const sample = all.slice(0, 5).join(', ');
    return (
      `Unknown element: ${tag}\n\n` +
      `Valid tags include: ${sample} (and ${Math.max(0, all.length - 5)} more).\n` +
      `Call component_reference with no name (or name: "list") to list all ${all.length} elements.`
    );
  }

  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────────
  lines.push(`## <${tag}>`);
  if (el.description) {
    lines.push('', el.description.trim());
  }

  // ── Contract note ──────────────────────────────────────────────────────────
  lines.push(
    '',
    '### AI/UI contract',
    '`kai-*` elements accept **array and object data as JavaScript properties** ' +
      '(set in JavaScript via `el.property = value`, not as HTML attributes). ' +
      'Events are native CustomEvents — listen with `el.addEventListener("event-name", handler)` ' +
      'and read `event.detail` for the payload.',
  );

  // ── Card contract ─────────────────────────────────────────────────────────
  // Attached to the two populations manifest.ts derives, and to nothing else. A
  // reference that hangs card material off all 80 elements is worse than one that
  // hangs it off none: it teaches a harness that every element takes a tool call.
  const cardType = cardTypeForTag(tag);
  if (cardType !== undefined && isCardSchemaName(cardType)) {
    lines.push(...renderCardContract(tag, cardType, provider));
  } else if (cardHostTags().includes(tag)) {
    lines.push(...renderCardHost(tag));
  }

  // ── Public JS properties ───────────────────────────────────────────────────
  const publicFields = (el.members ?? []).filter(
    (m) => m.kind === 'field' && m.privacy === 'public',
  );

  if (publicFields.length > 0) {
    lines.push('', '### Props (JavaScript properties)');
    for (const field of publicFields) {
      const type = field.type?.text ?? 'unknown';
      const jsOnly = isJsOnlyType(type);
      const desc = field.description?.trim() ?? '';
      const note = jsOnly ? ' ⚑ set as a JS property, not an HTML attribute' : '';
      lines.push(`- **${field.name}** \`${type}\`${note}`);
      if (desc) {
        lines.push(`  ${desc}`);
      }
    }
  }

  // ── HTML attributes ────────────────────────────────────────────────────────
  const attrs = el.attributes ?? [];
  if (attrs.length > 0) {
    lines.push('', '### Attributes (HTML-safe)');
    for (const attr of attrs) {
      const type = attr.type?.text ?? 'unknown';
      const desc = attr.description?.trim() ?? '';
      lines.push(`- **${attr.name}** \`${type}\``);
      if (desc) {
        lines.push(`  ${desc}`);
      }
    }
  }

  // ── Events ────────────────────────────────────────────────────────────────
  const events = el.events ?? [];
  if (events.length > 0) {
    lines.push('', '### Events (CustomEvent, listen via addEventListener)');
    for (const ev of events) {
      const desc = ev.description?.trim() ?? '';
      lines.push(`- **${ev.name}** — ${desc}`);
    }
  }

  // ── CSS custom properties ─────────────────────────────────────────────────
  const cssProps = el.cssProperties ?? [];
  if (cssProps.length > 0) {
    lines.push('', '### CSS custom properties');
    for (const prop of cssProps) {
      const desc = prop.description?.trim() ?? '';
      const def = prop.default ? ` (default: ${prop.default})` : '';
      lines.push(`- **${prop.name}**${def}${desc ? ` — ${desc}` : ''}`);
    }
  }

  // ── Composition slots ──────────────────────────────────────────────────────
  const slots = el.slots ?? [];
  if (slots.length > 0) {
    lines.push(
      '',
      '### Composition slots',
      'Project your own markup into these named regions — add a light-DOM child ' +
        'with a `slot="…"` attribute (e.g. `<div slot="sidebar">…</div>`).',
    );
    for (const slot of slots) {
      const desc = slot.description?.trim() ?? '';
      lines.push(`- **${slot.name}**${desc ? ` — ${desc}` : ''}`);
    }
  }

  // ── Styleable parts (::part) ───────────────────────────────────────────────
  const parts = el.cssParts ?? [];
  if (parts.length > 0) {
    lines.push(
      '',
      '### Styleable parts (`::part`)',
      'Restyle these from outside the Shadow DOM via `' + tag + '::part(name) { … }`.',
    );
    for (const part of parts) {
      const desc = part.description?.trim() ?? '';
      lines.push(`- **${part.name}**${desc ? ` — ${desc}` : ''}`);
      if (part.recipe) {
        lines.push('  ```css', `  ${part.recipe}`, '  ```');
      }
    }
  }

  return lines.join('\n');
}

export const reference: Tool = {
  name: 'component_reference',
  description:
    'Look up AI/UI (kai-*) web components: their tags, props, events, and usage examples. ' +
    'For a card-backed element it also returns the card\'s JSON Schema and a ready-to-send ' +
    'tool definition generated from it — pass `provider` to get that provider\'s envelope.',
  inputSchema: z.object({
    name: z.string().optional(),
    provider: z
      .enum(PROVIDERS)
      .optional()
      .describe(
        'Which tool-definition envelope to project for a card-backed element. ' +
          `Defaults to "${DEFAULT_PROVIDER}", the provider-neutral { name, description, schema } form.`,
      ),
  }),
  handler: async (args: Record<string, unknown>) => {
    const name = typeof args.name === 'string' ? args.name.trim() : undefined;

    // Validated HERE, not left to the zod schema above. server.ts advertises
    // `inputSchema` over the protocol but hands `request.params.arguments` straight
    // to this handler without parsing it, so an unrecognised provider would reach
    // `cardTools`, which treats anything that is not "openai"/"anthropic" as the
    // jsonschema branch. A caller asking for "gemini" would then get a definition in
    // a shape they did not ask for, with nothing saying so. Refusing is the only
    // answer that cannot be mistaken for an answer.
    const rawProvider = args.provider;
    if (rawProvider !== undefined && (typeof rawProvider !== 'string' || !isProvider(rawProvider))) {
      return {
        content: [
          {
            type: 'text' as const,
            text:
              `Unknown provider: ${JSON.stringify(rawProvider)}\n\n` +
              `Valid providers are ${PROVIDERS.map((p) => `"${p}"`).join(', ')}. ` +
              `Omit it to get "${DEFAULT_PROVIDER}", the provider-neutral { name, description, schema } form ` +
              'that the Vercel AI SDK and most agent frameworks take directly.\n' +
              'No tool definition was returned, because guessing which envelope you meant would hand you ' +
              'a shape your provider rejects with nothing saying why.',
          },
        ],
      };
    }
    const provider: ToolProvider = rawProvider ?? DEFAULT_PROVIDER;

    let text: string;

    if (!name || name === 'list') {
      const tags = listElements();
      const cardRows = cardSchemaNames
        .map((t) => cardTagForType(t))
        .filter((t): t is string => t !== undefined);
      text =
        `AI/UI elements (${tags.length} total):\n\n` +
        tags.map((t) => `  ${t}`).join('\n') +
        '\n\nCall component_reference with a specific name (e.g. { name: "kai-chat" }) for full API details.' +
        `\n\nCard-backed elements — ask for one of these to get its JSON Schema and a generated ` +
        `\`${KAI_TOOL_PREFIX}*\` tool definition:\n  ${cardRows.join(', ')}` +
        `\nThe elements that HOST them (and carry the \`cardTypes\` / \`cardSchemas\` props): ${cardHostTags().join(', ')}`;
    } else {
      text = formatReference(name, provider);
    }

    return { content: [{ type: 'text' as const, text }] };
  },
};
