// The compiled Tailwind stylesheet as a raw string, so it can be adopted into
// the panel's shadow root. Mirrors the kit's own `src/elements/css.ts`.
//
// Generated by `npm run build:css`, wired as `prebuild` -- a bare `vite build`
// therefore cannot emit an unstyled panel.
import compiled from './compiled.css?inline';

export const PANEL_CSS: string = compiled;

/**
 * Adopt the stylesheet into a shadow root BEFORE first paint.
 *
 * Constructable stylesheets are shared across instances rather than duplicating
 * ~120 KB of inline CSS each; where unavailable, a `<style>` node is appended.
 * Both must happen before anything renders, which is the kit's own documented
 * gotcha: adopt after first paint and the panel flashes unstyled.
 */
let sharedSheet: CSSStyleSheet | null | undefined;

export function adoptPanelCss(root: ShadowRoot): void {
  if (sharedSheet === undefined) {
    try {
      if (typeof CSSStyleSheet === 'undefined') throw new Error('no CSSStyleSheet');
      const sheet = new CSSStyleSheet();
      sheet.replaceSync(PANEL_CSS);
      sharedSheet = sheet;
    } catch {
      sharedSheet = null;
    }
  }
  if (sharedSheet) {
    root.adoptedStyleSheets = [...root.adoptedStyleSheets, sharedSheet];
    return;
  }
  const style = document.createElement('style');
  style.textContent = PANEL_CSS;
  root.appendChild(style);
}
