// src/elements/resizable.globals.d.ts
// Hand-authored ambient types for <kai-resizable>'s maximize capability. The
// generated element-types.d.ts emits prop/event interfaces only (not methods),
// so the imperative host API + the cross-element protocol events live here.
// NOT regenerated by `npm run build`.
//
// THE FILENAME IS LOAD-BEARING and must not go back to `resizable.d.ts`.
// TypeScript drops a .d.ts when a same-named .ts/.tsx sits beside it, and
// `resizable.tsx` does. Under the old name this whole file was in NO tsc
// program, so every augmentation below was inert. Measured on the same probe,
// `el.addEventListener('kai-maximize-intent', e => e.detail)`:
//   resizable.d.ts         TS2339: Property 'detail' does not exist on 'Event'
//   resizable.globals.d.ts clean -- narrowed to CustomEvent<KaiMaximizeIntentDetail>
//
// KNOWN BROKEN, and the rename does NOT fix it: the HTMLElementTagNameMap entry
// below loses to the generated one. element-types.d.ts declares its own
// module-scoped `export interface KaiResizableElement` and maps 'kai-resizable'
// to THAT, so `document.createElement('kai-resizable').maximize(0)` is still
// TS2339 -- identical before and after the rename. The two same-named types
// collide (TS2717 on line 19, visible only with `--skipLibCheck false`, which
// every pass sets true). `maximize`/`restore` therefore reach no caller. The fix
// belongs in scripts/gen-element-types.mjs -- either have it emit methods, or
// have this file augment the generated interface by module declaration instead
// of declaring a second global one of the same name.
import type { KaiMaximizeIntentDetail, KaiMaximizeStateDetail } from './resizable';

declare global {
  interface KaiResizableElement extends HTMLElement {
    /** Which item index is maximized (null = none). Setting it maximizes that
     *  item (or restores when set to null) — the declarative source of truth. */
    maximizedIndex: number | null;
    /** Imperatively maximize the item at `index` (thin wrapper over maximizedIndex). */
    maximize(index: number): void;
    /** Imperatively restore from the maximized layout. */
    restore(): void;
  }
  interface HTMLElementTagNameMap {
    'kai-resizable': KaiResizableElement;
  }
  interface HTMLElementEventMap {
    'kai-maximize-intent': CustomEvent<KaiMaximizeIntentDetail>;
    'kai-maximize-state': CustomEvent<KaiMaximizeStateDetail>;
  }
}

export {};
