/**
 * The feature multi-select — the CLI's surface axis.
 *
 * Each feature is a name for a `kai-*` components list. That is the whole
 * mapping, and it is what lets any combination be reachable instead of only the
 * six someone thought to name: the archetypes in the kit's catalog are six
 * points in this space, and `renderSurface` takes the list rather than a preset
 * id precisely so the rest of the space is expressible.
 *
 * WHAT IS DECLARED HERE AND WHY IT IS NOT A RESTATEMENT. The components are the
 * CLI's own product decision — "conversation history means a sidebar plus a
 * resizable split" is a UX call, not a fact the catalog holds. What is NOT
 * declared here is whether a feature can actually be emitted: that is computed
 * against `rendererComponents()` and the framework's template, so a feature
 * whose components no renderer branches on is reported as unavailable rather
 * than emitted into a project that silently lacks it.
 */
import { rendererComponents } from './catalog';
import type { FrameworkDef } from './frameworks';

export interface FeatureDef {
  id: string;
  label: string;
  hint: string;
  /** the `kai-*` components this feature composes */
  components: readonly string[];
  /** ticked when the user presses Enter through the prompt */
  default: boolean;
}

export const FEATURES: readonly FeatureDef[] = [
  {
    id: 'conversations',
    label: 'Conversation history',
    hint: 'sidebar of past chats, new-chat, switching',
    components: ['kai-conversations', 'kai-resizable'],
    default: true,
  },
  {
    id: 'sources',
    label: 'Sources and citations',
    hint: 'inline citations plus a sources panel',
    components: ['kai-sources'],
    default: false,
  },
  {
    id: 'agentic',
    label: 'Tools and reasoning',
    hint: 'tool-call panels plus reasoning disclosure',
    components: ['kai-tool', 'kai-reasoning'],
    default: false,
  },
  {
    id: 'artifacts',
    label: 'Artifacts and preview',
    hint: 'split view with a live artifact pane',
    components: ['kai-artifact', 'kai-resizable'],
    default: false,
  },
  {
    id: 'voice',
    label: 'Voice',
    hint: 'mic input',
    components: ['kai-voice-input'],
    default: false,
  },
  {
    id: 'attachments',
    label: 'Attachments',
    hint: 'file upload plus attachment chips',
    components: ['kai-file-upload', 'kai-attachments'],
    default: false,
  },
];

export function getFeature(id: string): FeatureDef | undefined {
  return FEATURES.find((f) => f.id === id);
}

/** The features ticked by default — the zero-config surface. */
export const DEFAULT_FEATURES: readonly string[] = FEATURES.filter((f) => f.default).map(
  (f) => f.id,
);

/**
 * How a feature reaches an emitted project, or why it cannot.
 *
 *   `composed` — comes from the framework's hand-composed workspace starter,
 *                copied verbatim. The reviewed, flagship path.
 *   `renderer` — generated by `renderSurface` from the components list.
 *   `unavailable` — neither. The components exist as elements, but no renderer
 *                branches on them and no starter composes them, so emitting the
 *                feature would produce a project that compiles and runs without
 *                the feature in it.
 */
export type FeatureEmit = 'composed' | 'renderer' | 'unavailable';

/**
 * The features that ONLY the hand-composed workspace starter can produce, named
 * once so `featureEmit` and the refusal message below cannot disagree about
 * which they are.
 *
 * `conversations` is here because `renderSurface` has no `kai-conversations`
 * branch: it takes any components list, and a tag it does not branch on is not
 * an error, just a tag it emits bare with nothing wired to it. So the sidebar
 * comes from the reviewed starter or it does not come at all.
 *
 * The way OUT of this set is the same one `attachments` took (see below): a
 * preset in the kit's archetype catalog composing the components, which puts
 * them in `listCapabilityGroups()` and gives `renderSurface` a real branch.
 */
const COMPOSED_ONLY: ReadonlySet<string> = new Set(['conversations']);

/**
 * DISCOVERED, NOT HARD-CODED — and `attachments` is the proof rather than the
 * example.
 *
 * This function used to report `attachments` as `unavailable`, because
 * `kai-file-upload` / `kai-attachments` were real registered elements that no
 * archetype composed: `listCapabilityGroups()` did not report them, so
 * `renderSurface` had no branch and emitting the feature would have produced a
 * project that compiled, ran, and did not have the feature in it. The comment
 * here said "add an archetype using those components and the feature becomes
 * available with no edit here". That happened, upstream in the kit, and this
 * file was not edited — the feature is `renderer` now because the derivation
 * says so.
 *
 * The gap that remains is `conversations`, and it is a DIFFERENT gap: not
 * "nothing renders these components" but "only a hand-written starter composes
 * this surface", which is why the two paths below report separately.
 */
export function featureEmit(feature: FeatureDef, framework: FrameworkDef): FeatureEmit {
  if (COMPOSED_ONLY.has(feature.id)) {
    return framework.composedWorkspace ? 'composed' : 'unavailable';
  }
  const known = rendererComponents();
  return feature.components.every((c) => known.has(c)) ? 'renderer' : 'unavailable';
}

/**
 * Why a feature cannot be emitted, in the words a user should see.
 *
 * Split by CAUSE rather than printed as one sentence covering both, because the
 * single sentence this replaces was wrong the moment `conversations` became the
 * only unavailable feature: it read "no renderer branches on kai-conversations /
 * kai-resizable", and a renderer plainly does branch on `kai-resizable`. A
 * refusal that misstates its own reason sends the reader after the wrong fix.
 *
 * Returns null when the feature IS emittable, so the caller cannot print a
 * reason for a feature that has none.
 */
export function featureUnavailableReason(
  feature: FeatureDef,
  framework: FrameworkDef,
): string | null {
  if (featureEmit(feature, framework) !== 'unavailable') return null;
  if (COMPOSED_ONLY.has(feature.id)) {
    return (
      `feature '${feature.id}' cannot be emitted for ${framework.label}: it comes from the ` +
      `hand-composed workspace starter and ${framework.label} has none. No renderer emits a ` +
      `${feature.components[0]} surface, so there is nothing to generate in its place.`
    );
  }
  const known = rendererComponents();
  const missing = feature.components.filter((c) => !known.has(c));
  return (
    `feature '${feature.id}' cannot be emitted for ${framework.label}: no renderer branches on ` +
    `${missing.join(' / ')}, so the emitted project would compile and run without the feature ` +
    `in it. Compose those components in a kit archetype and this resolves itself.`
  );
}

/** The features the prompt offers for a given framework. */
export function availableFeatures(framework: FrameworkDef): FeatureDef[] {
  return FEATURES.filter((f) => featureEmit(f, framework) !== 'unavailable');
}

/**
 * Resolve a chosen feature set to the surface the generator must produce.
 *
 * The composed workspace is a whole reviewed template rather than a components
 * list, so it cannot be mixed with generated capabilities in this slice: asking
 * for `conversations` + `agentic` would mean patching tool panels into
 * hand-written JSX, which is the kind of surgery that emits something that looks
 * right. Rejected explicitly here instead.
 */
export type Surface =
  | { kind: 'composed'; features: readonly string[] }
  | { kind: 'generated'; features: readonly string[]; components: readonly string[] };

export function resolveSurface(
  featureIds: readonly string[],
  framework: FrameworkDef,
): { ok: true; surface: Surface } | { ok: false; reason: string } {
  const chosen: FeatureDef[] = [];
  for (const id of featureIds) {
    const feature = getFeature(id);
    if (!feature) return { ok: false, reason: `unknown feature '${id}'` };
    const unavailable = featureUnavailableReason(feature, framework);
    if (unavailable) return { ok: false, reason: unavailable };
    chosen.push(feature);
  }

  const composed = chosen.filter((f) => featureEmit(f, framework) === 'composed');
  if (composed.length > 0) {
    if (chosen.length > composed.length) {
      const extra = chosen.filter((f) => !composed.includes(f)).map((f) => f.id);
      return {
        ok: false,
        reason:
          `'${composed.map((f) => f.id).join("', '")}' comes from the hand-composed workspace ` +
          `template, which this release cannot combine with generated features ` +
          `('${extra.join("', '")}'). Pick one or the other.`,
      };
    }
    return { ok: true, surface: { kind: 'composed', features: featureIds } };
  }

  // `kai-chat` is the base every surface composes around; capabilities add to it.
  const components = ['kai-chat', ...new Set(chosen.flatMap((f) => f.components))];
  return { ok: true, surface: { kind: 'generated', features: featureIds, components } };
}
