/**
 * The feature multi-select — the CLI's surface axis.
 *
 * Each feature is a name for a `kai-*` components list. That is the whole
 * mapping, and it is what lets any combination be reachable instead of only the
 * six someone thought to name: the archetypes in the kit's catalog are six
 * points in this space, and `renderSurface` takes the list rather than a preset
 * id precisely so the rest of the space is expressible.
 *
 * WHAT IS DECLARED HERE AND WHY IT IS NOT A RESTATEMENT. The components are the
 * CLI's own product decision — "conversation history means a sidebar plus a
 * resizable split" is a UX call, not a fact the catalog holds. What is NOT
 * declared here is whether a feature can actually be emitted: that is computed
 * against `rendererComponents()` and the framework's template, so a feature
 * whose components no renderer branches on is reported as unavailable rather
 * than emitted into a project that silently lacks it.
 */
import { rendererComponents } from './catalog';
import type { FrameworkDef } from './frameworks';

export interface FeatureDef {
  id: string;
  label: string;
  hint: string;
  /** the `kai-*` components this feature composes */
  components: readonly string[];
  /** ticked when the user presses Enter through the prompt */
  default: boolean;
}

export const FEATURES: readonly FeatureDef[] = [
  {
    id: 'conversations',
    label: 'Conversation history',
    hint: 'sidebar of past chats, new-chat, switching',
    components: ['kai-conversations', 'kai-resizable'],
    default: true,
  },
  {
    id: 'sources',
    label: 'Sources and citations',
    hint: 'inline citations plus a sources panel',
    components: ['kai-sources'],
    default: false,
  },
  {
    id: 'agentic',
    label: 'Tools and reasoning',
    hint: 'tool-call panels plus reasoning disclosure',
    components: ['kai-tool', 'kai-reasoning'],
    default: false,
  },
  {
    id: 'artifacts',
    label: 'Artifacts and preview',
    hint: 'split view with a live artifact pane',
    components: ['kai-artifact', 'kai-resizable'],
    default: false,
  },
  {
    id: 'voice',
    label: 'Voice',
    hint: 'mic input',
    components: ['kai-voice-input'],
    default: false,
  },
  {
    id: 'attachments',
    label: 'Attachments',
    hint: 'file upload plus attachment chips',
    components: ['kai-file-upload', 'kai-attachments'],
    default: false,
  },
];

export function getFeature(id: string): FeatureDef | undefined {
  return FEATURES.find((f) => f.id === id);
}

/** The features ticked by default — the zero-config surface. */
export const DEFAULT_FEATURES: readonly string[] = FEATURES.filter((f) => f.default).map(
  (f) => f.id,
);

/**
 * How a feature reaches an emitted project, or why it cannot.
 *
 *   `composed` — comes from the framework's hand-composed workspace starter,
 *                copied verbatim. The reviewed, flagship path.
 *   `renderer` — generated by `renderSurface` from the components list.
 *   `unavailable` — neither. The components exist as elements, but no renderer
 *                branches on them and no starter composes them, so emitting the
 *                feature would produce a project that compiles and runs without
 *                the feature in it.
 */
export type FeatureEmit = 'composed' | 'renderer' | 'unavailable';

/**
 * `attachments` is `unavailable` today, and that is a REPORTED GAP rather than a
 * decision: `kai-file-upload` and `kai-attachments` are real registered
 * elements, but no archetype composes them, so `listCapabilityGroups()` does not
 * report them and `renderSurface` has no branch that emits them. This function
 * discovers that rather than hard-coding it — add an archetype using those
 * components (or a renderer branch reflected in one) and the feature becomes
 * available with no edit here.
 */
export function featureEmit(feature: FeatureDef, framework: FrameworkDef): FeatureEmit {
  // The composed workspace IS conversation history; it is the only source of a
  // `kai-conversations` surface today.
  if (feature.id === 'conversations') {
    return framework.composedWorkspace ? 'composed' : 'unavailable';
  }
  const known = rendererComponents();
  return feature.components.every((c) => known.has(c)) ? 'renderer' : 'unavailable';
}

/** The features the prompt offers for a given framework. */
export function availableFeatures(framework: FrameworkDef): FeatureDef[] {
  return FEATURES.filter((f) => featureEmit(f, framework) !== 'unavailable');
}

/**
 * Resolve a chosen feature set to the surface the generator must produce.
 *
 * The composed workspace is a whole reviewed template rather than a components
 * list, so it cannot be mixed with generated capabilities in this slice: asking
 * for `conversations` + `agentic` would mean patching tool panels into
 * hand-written JSX, which is the kind of surgery that emits something that looks
 * right. Rejected explicitly here instead.
 */
export type Surface =
  | { kind: 'composed'; features: readonly string[] }
  | { kind: 'generated'; features: readonly string[]; components: readonly string[] };

export function resolveSurface(
  featureIds: readonly string[],
  framework: FrameworkDef,
): { ok: true; surface: Surface } | { ok: false; reason: string } {
  const chosen: FeatureDef[] = [];
  for (const id of featureIds) {
    const feature = getFeature(id);
    if (!feature) return { ok: false, reason: `unknown feature '${id}'` };
    const emit = featureEmit(feature, framework);
    if (emit === 'unavailable') {
      return {
        ok: false,
        reason:
          `feature '${id}' cannot be emitted for ${framework.label}: no renderer branches on ` +
          `${feature.components.join(' / ')} and no starter composes them`,
      };
    }
    chosen.push(feature);
  }

  const composed = chosen.filter((f) => featureEmit(f, framework) === 'composed');
  if (composed.length > 0) {
    if (chosen.length > composed.length) {
      const extra = chosen.filter((f) => !composed.includes(f)).map((f) => f.id);
      return {
        ok: false,
        reason:
          `'${composed.map((f) => f.id).join("', '")}' comes from the hand-composed workspace ` +
          `template, which this release cannot combine with generated features ` +
          `('${extra.join("', '")}'). Pick one or the other.`,
      };
    }
    return { ok: true, surface: { kind: 'composed', features: featureIds } };
  }

  // `kai-chat` is the base every surface composes around; capabilities add to it.
  const components = ['kai-chat', ...new Set(chosen.flatMap((f) => f.components))];
  return { ok: true, surface: { kind: 'generated', features: featureIds, components } };
}
