/**
 * The feature multi-select — the CLI's surface axis.
 *
 * Each feature is a name for a `kai-*` components list. That is the whole
 * mapping, and it is what lets any combination be reachable instead of only the
 * six someone thought to name: the archetypes in the kit's catalog are six
 * points in this space, and `renderSurface` takes the list rather than a preset
 * id precisely so the rest of the space is expressible.
 *
 * WHAT IS DECLARED HERE AND WHY IT IS NOT A RESTATEMENT. The components are the
 * CLI's own product decision — "conversation history means a sidebar plus a
 * resizable split" is a UX call, not a fact the catalog holds. What is NOT
 * declared here is whether a feature can actually be emitted: that is computed,
 * against `rendererComponents()`, the framework's template, and whether the
 * generator has the surface path at all (`GENERATED_SURFACES_WIRED`). So a
 * feature nothing can produce is reported as unavailable rather than offered in
 * a menu and refused after the last prompt.
 *
 * THE TABLE BELOW IS THE CATALOG, NOT THE MENU. Every entry stays declared while
 * it is unbuildable — `--list` prints the whole table with what can be
 * scaffolded marked — and `availableFeatures()` is the only thing the prompt
 * reads. Deleting a row would hide the gap; offering one hides the same gap
 * behind a menu item that fails.
 */
import { rendererComponents } from './catalog';
import type { FrameworkDef } from './frameworks';

export interface FeatureDef {
  id: string;
  label: string;
  hint: string;
  /** the `kai-*` components this feature composes */
  components: readonly string[];
  /** ticked when the user presses Enter through the prompt */
  default: boolean;
}

export const FEATURES: readonly FeatureDef[] = [
  {
    id: 'conversations',
    label: 'Conversation history',
    hint: 'sidebar of past chats, new-chat, switching',
    components: ['kai-conversations', 'kai-resizable'],
    default: true,
  },
  {
    id: 'sources',
    label: 'Sources and citations',
    hint: 'inline citations plus a sources panel',
    components: ['kai-sources'],
    default: false,
  },
  {
    id: 'agentic',
    label: 'Tools and reasoning',
    hint: 'tool-call panels plus reasoning disclosure',
    components: ['kai-tool', 'kai-reasoning'],
    default: false,
  },
  {
    id: 'artifacts',
    label: 'Artifacts and preview',
    hint: 'split view with a live artifact pane',
    components: ['kai-artifact', 'kai-resizable'],
    default: false,
  },
  {
    id: 'voice',
    label: 'Voice',
    hint: 'mic input',
    components: ['kai-voice-input'],
    default: false,
  },
  {
    id: 'attachments',
    label: 'Attachments',
    hint: 'file upload plus attachment chips',
    components: ['kai-file-upload', 'kai-attachments'],
    default: false,
  },
];

export function getFeature(id: string): FeatureDef | undefined {
  return FEATURES.find((f) => f.id === id);
}

/** The features ticked by default — the zero-config surface. */
export const DEFAULT_FEATURES: readonly string[] = FEATURES.filter((f) => f.default).map(
  (f) => f.id,
);

/**
 * How a feature reaches an emitted project, or why it cannot.
 *
 *   `composed` — comes from the framework's hand-composed workspace starter,
 *                copied verbatim. The reviewed, flagship path.
 *   `renderer` — generated by `renderSurface` from the components list.
 *   `unavailable` — neither. So emitting the feature would produce a project
 *                that compiles and runs without the feature in it.
 */
export type FeatureEmit = 'composed' | 'renderer' | 'unavailable';

/**
 * Whether `generate()` can emit a `renderSurface`-generated surface AT ALL.
 *
 * THIS IS THE ONE FACT BEHIND EVERYTHING THE MENU DOES NOT OFFER, and it is
 * declared here rather than in five places because it shipped as five places.
 * `create-kai@0.1.4` offered six features and scaffolded one: `featureEmit`
 * answered "the renderer knows every component this feature names", the prompt
 * read that as "this feature scaffolds", and `generate()` — which has no
 * generated-surface path at all — threw AFTER the user had answered every
 * prompt. Nothing was wrong with the derivation; it was answering a weaker
 * question than the caller was asking.
 *
 * So the emittability answer now includes the generator, and it is the ONLY
 * thing the prompt reads — the menu cannot claim a surface this does not admit
 * to having.
 *
 * TURNING IT ON IS NOT A ONE-LINE EDIT, and nothing here trusts that it is. The
 * work is: patch `renderSurface`'s output into each framework's entry file, and
 * RUN one of the resulting projects — `ready` means run here for the same reason
 * it does in `frameworks.ts`. `generate()`'s own refusal is deliberately NOT
 * gated on this constant (see the comment at it), so flipping this alone turns
 * `test/menu-honesty.test.ts` red rather than shipping a menu of features that
 * emit the composed starter under another name.
 *
 * The type is `boolean` rather than the literal `false` so the renderer branches
 * below stay live code while it is off.
 */
export const GENERATED_SURFACES_WIRED: boolean = false;

/**
 * Why, in the words a user should see. One string, quoted by the prompt's
 * refusal and by `generate()`'s, so a reader who hits either finds the same
 * sentence and the same fix.
 */
export const GENERATED_SURFACE_GAP =
  'generated feature surfaces are not wired in this release — no such project has been ' +
  'run end to end, so emitting one would hand back an app nobody has seen work. The ' +
  'composed workspace is the surface that runs today';

/**
 * The features that ONLY the hand-composed workspace starter can produce, named
 * once so `featureEmit` and the refusal message below cannot disagree about
 * which they are.
 *
 * `conversations` is here because `renderSurface` has no `kai-conversations`
 * branch: it takes any components list, and a tag it does not branch on is not
 * an error, just a tag it emits bare with nothing wired to it. So the sidebar
 * comes from the reviewed starter or it does not come at all.
 *
 * The way OUT of this set is the same one `attachments` took (see below): a
 * preset in the kit's archetype catalog composing the components, which puts
 * them in `listCapabilityGroups()` and gives `renderSurface` a real branch.
 */
const COMPOSED_ONLY: ReadonlySet<string> = new Set(['conversations']);

/**
 * DISCOVERED, NOT HARD-CODED — and `attachments` is the proof rather than the
 * example.
 *
 * This function used to report `attachments` as `unavailable`, because
 * `kai-file-upload` / `kai-attachments` were real registered elements that no
 * archetype composed: `listCapabilityGroups()` did not report them, so
 * `renderSurface` had no branch and emitting the feature would have produced a
 * project that compiled, ran, and did not have the feature in it. The comment
 * here said "add an archetype using those components and the feature becomes
 * available with no edit here". That happened, upstream in the kit, and this
 * file was not edited — the feature is `renderer` now because the derivation
 * says so.
 *
 * The gap that remains is `conversations`, and it is a DIFFERENT gap: not
 * "nothing renders these components" but "only a hand-written starter composes
 * this surface", which is why the two paths below report separately.
 */
export function featureEmit(feature: FeatureDef, framework: FrameworkDef): FeatureEmit {
  if (COMPOSED_ONLY.has(feature.id)) {
    return framework.composedWorkspace ? 'composed' : 'unavailable';
  }
  const known = rendererComponents();
  if (!feature.components.every((c) => known.has(c))) return 'unavailable';
  // The renderer knowing every component is NOT the same as the CLI being able
  // to emit the surface, and treating the first as the second is the whole of
  // the 0.1.4 defect. Both gates, in the order that names the deeper cause
  // first: a feature whose components nothing renders is a kit-catalog gap, and
  // a feature the generator cannot emit is a gap in this package.
  return GENERATED_SURFACES_WIRED ? 'renderer' : 'unavailable';
}

/**
 * Why a feature cannot be emitted, in the words a user should see.
 *
 * Split by CAUSE rather than printed as one sentence covering both, because the
 * single sentence this replaces was wrong the moment `conversations` became the
 * only unavailable feature: it read "no renderer branches on kai-conversations /
 * kai-resizable", and a renderer plainly does branch on `kai-resizable`. A
 * refusal that misstates its own reason sends the reader after the wrong fix.
 *
 * Returns null when the feature IS emittable, so the caller cannot print a
 * reason for a feature that has none.
 */
export function featureUnavailableReason(
  feature: FeatureDef,
  framework: FrameworkDef,
): string | null {
  if (featureEmit(feature, framework) !== 'unavailable') return null;
  if (COMPOSED_ONLY.has(feature.id)) {
    return (
      `feature '${feature.id}' cannot be emitted for ${framework.label}: it comes from the ` +
      `hand-composed workspace starter and ${framework.label} has none. No renderer emits a ` +
      `${feature.components[0]} surface, so there is nothing to generate in its place.`
    );
  }
  const known = rendererComponents();
  const missing = feature.components.filter((c) => !known.has(c));
  if (missing.length > 0) {
    return (
      `feature '${feature.id}' cannot be emitted for ${framework.label}: no renderer branches on ` +
      `${missing.join(' / ')}, so the emitted project would compile and run without the feature ` +
      `in it. Compose those components in a kit archetype and this resolves itself.`
    );
  }
  return `feature '${feature.id}' cannot be emitted: ${GENERATED_SURFACE_GAP}.`;
}

/**
 * The features the prompt offers for a given framework.
 *
 * THE PROMPT'S LIST IS THIS LIST. `test/menu-honesty.test.ts` drives every entry
 * it returns through `generate()` against the real templates, so an option that
 * cannot be scaffolded fails a test rather than a user — which is the guard the
 * six-item menu never had.
 */
export function availableFeatures(framework: FrameworkDef): FeatureDef[] {
  return FEATURES.filter((f) => featureEmit(f, framework) !== 'unavailable');
}

/**
 * The features the framework's composed workspace starter puts in the project,
 * whether or not they were asked for.
 *
 * The starter is copied VERBATIM — it is one reviewed tree, not a set of parts
 * that can be left out — so this is what an emitted project has. It exists as a
 * function because two callers need it and neither may guess: `resolveSurface`
 * records it in the surface (so `kai.json` describes the project rather than the
 * request), and the prompt states it instead of offering it as a choice.
 */
export function composedWorkspaceFeatures(framework: FrameworkDef): FeatureDef[] {
  return FEATURES.filter((f) => featureEmit(f, framework) === 'composed');
}

/**
 * Resolve a chosen feature set to the surface the generator must produce.
 *
 * The composed workspace is a whole reviewed template rather than a components
 * list, so it cannot be mixed with generated capabilities in this slice: asking
 * for `conversations` + `agentic` would mean patching tool panels into
 * hand-written JSX, which is the kind of surgery that emits something that looks
 * right. Rejected explicitly here instead.
 */
export type Surface =
  | {
      kind: 'composed';
      /**
       * What the emitted project HAS, not what was asked for — the two differ
       * whenever the starter carries a feature the user did not tick, and
       * `kai.json` is written from this so it describes the project on disk.
       */
      features: readonly string[];
      /**
       * The features in `features` that were NOT asked for. The caller states
       * them; a scaffold that quietly includes what nobody picked is a decision
       * made while withholding that it happened.
       */
      unasked: readonly string[];
    }
  | { kind: 'generated'; features: readonly string[]; components: readonly string[] };

export function resolveSurface(
  featureIds: readonly string[],
  framework: FrameworkDef,
): { ok: true; surface: Surface } | { ok: false; reason: string } {
  const chosen: FeatureDef[] = [];
  for (const id of featureIds) {
    const feature = getFeature(id);
    if (!feature) return { ok: false, reason: `unknown feature '${id}'` };
    const unavailable = featureUnavailableReason(feature, framework);
    if (unavailable) return { ok: false, reason: unavailable };
    chosen.push(feature);
  }

  const composed = chosen.filter((f) => featureEmit(f, framework) === 'composed');
  // AN EMPTY SELECTION IS AN ANSWER, and while the generated path is unwired it
  // is answered by the same starter every other selection gets. It used to
  // resolve to a bare generated `kai-chat` and so hit the refusal below — which
  // meant deselecting everything in the prompt, and `--features none`, both
  // failed after the last question. There is no bare-chat template to emit; the
  // honest reply is the one surface this release has, said out loud through
  // `unasked`.
  if (composed.length > 0 || (chosen.length === 0 && !GENERATED_SURFACES_WIRED)) {
    if (chosen.length > composed.length) {
      const extra = chosen.filter((f) => !composed.includes(f)).map((f) => f.id);
      return {
        ok: false,
        reason:
          `'${composed.map((f) => f.id).join("', '")}' comes from the hand-composed workspace ` +
          `template, which this release cannot combine with generated features ` +
          `('${extra.join("', '")}'). Pick one or the other.`,
      };
    }
    // The starter is one reviewed tree, so the project gets all of what it
    // composes regardless of which subset was asked for.
    const emitted = composedWorkspaceFeatures(framework);
    if (emitted.length === 0) {
      return {
        ok: false,
        reason:
          `'${framework.label}' has no composed workspace starter, and ${GENERATED_SURFACE_GAP}. ` +
          'There is no surface to emit for it.',
      };
    }
    const asked = new Set(featureIds);
    return {
      ok: true,
      surface: {
        kind: 'composed',
        features: emitted.map((f) => f.id),
        unasked: emitted.filter((f) => !asked.has(f.id)).map((f) => f.id),
      },
    };
  }

  return {
    ok: true,
    surface: { kind: 'generated', features: featureIds, components: surfaceComponents(chosen) },
  };
}

/**
 * The components list `renderSurface` is handed for a generated surface.
 *
 * A NAMED FUNCTION BECAUSE IT IS THE ONLY WAY TO TEST IT HONESTLY while
 * `GENERATED_SURFACES_WIRED` is off. Inline in `resolveSurface` it is
 * unreachable — nothing gets past the feature gate to produce one — so the tests
 * over it would have had to be deleted, and the de-duplication rule below is
 * exactly the kind of thing that comes back wrong when the path is wired months
 * later. Testing the piece directly keeps the coverage real instead of vacuous.
 *
 * `kai-chat` is the base every surface composes around; capabilities add to it,
 * and a component two features share is emitted once — a duplicate tag is a
 * rendered element twice.
 */
export function surfaceComponents(chosen: readonly FeatureDef[]): string[] {
  return ['kai-chat', ...new Set(chosen.flatMap((f) => f.components))];
}
